config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :hotels, :only => [:show, :index] do
    resources :comments, :only => [:show, :create]
  end

  root 'hotels#index'
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name, type: String
  field :description, type: String

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }

  embedded_in :hotel, inverse_of: :comments
end

app/models/hotel.rb
class Hotel
  include Mongoid::Document
  field :name, type: String
  field :city, type: String
  field :address, type: String
  field :latitude, type: Float
  field :longitude, type: Float

  embeds_one :review
  embeds_many :comments

  accepts_nested_attributes_for :comments

  # Search
  def self.search(search)
    if search
      any_of({name: /#{search}/i},{'review.text': /#{search}/i})
    end
  end
end

app/models/review.rb
class Review
  include Mongoid::Document
  
  field :title, type: String
  field :text, type: String
  field :rating, type: Integer

  embedded_in :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_hotel
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @hotel.comments.build(comment_params)
    
    if @comment.save
      flash[:success] = "Comment was successfully posted." # flash message
      redirect_to hotel_path(@hotel) # redirect to hotel(:id)
    else
      flash[:error] = "Form didn't validate, please check fields."
      redirect_to request.referrer # redirect to same page
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def catch_404
    raise ActionController::RoutingError.new(params[:path])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :description)
    end

    def load_hotel
      @hotel = Hotel.find(params[:hotel_id]) || []
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    sleep 2
    if params[:search].blank?
      @hotels = Hotel.all.paginate(:page => params[:page], :per_page => 20)
    else
      @hotels = Hotel.search(params[:search]).paginate(:page => params[:page], :per_page => 20)
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel_comments = @hotel.comments.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def catch_404
    raise ActionController::RoutingError.new(params[:path])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :city, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/comments/_comment.html.erb
<% obj.each do |comment| %>
<div class="ui fluid teal label">
    <div class="description">
        <div class="item">
            <div class="content">
            <h2 class="header"><i class="circle user icon"></i> <%= comment.name %></h2>
            <div class="description">
                <p><i class="paper plane icon"></i> <%= comment.description %></p>
            </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, :html => {class: "ui form"}) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :comment_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :comment_description %>
  </div>

  <button class="ui button" type="submit"><%= semantic_icon('paper plane')+'Post' %></button>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Hotel</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.hotel_id %></td>
        <td><%= comment.name %></td>
        <td><%= comment.description %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hotel:</strong>
  <%= @comment.hotel_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/hotels/_form.html.erb
<%= form_for([@hotel, Comment.new], html: { class: 'ui form' }) do |form| %>
    <div class="field">
      <label>Username (min: 3, max: 50 words)</label>
      <%= form.text_field :name, id: :comment_name, placeholder: 'Your name' %>
    </div>
  
    <div class="field">
      <label>Comment (min: 5, max: 300 words)</label>
      <%= form.text_area :description, id: :comment_description, placeholder: 'Add comment...' %>
    </div>

  <button class="ui button" type="submit"><%= semantic_icon('paper plane')+'Post' %></button>

<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $(".rating").rating('disable');
      $('.caret.down').transition('set looping').transition('bounce', '2000ms');
  });
</script>

<div class="cover"></div>

<div id="wrapper">
  <h1>Hotel Reviews</h1>
    <br>
  <h2 class="center aligned">Find the best hotels by reading other reviews.</h2>
    <br>
  <i class="big caret down icon"></i>
</div>

<br>

<div class="ui large red tag label">Found <%= number_with_delimiter(@hotels.total_entries, :delimiter => ",") %> hotel reviews!</div>

<br>

<% if @hotels.size == 0 %>
  <div class="ui fluid card">
    <div class="content">
      <h1 class="center aligned header">No hotel reviews found.</h1>
    </div>
  </div>
<% else %>
  <% @hotels.each do |hotel| %>
    <div class="ui fluid card">
      <div class="content">
        <div class="ui teal ribbon label">
          <h1 class="header"><i class="hotel icon"></i> <%= hotel.name %></h1>
          <div class="meta"><%= hotel.address %></div>
          <div class="meta"><%= hotel.city %></div>
        </div>
        <div class="description">
          <p><%= hotel.review.title %></p>
          <p><%= truncate(hotel.review.text, length: 250) %></p>
        </div>
        </div>
        <div class="extra content">
          <div class="ui large label">Rating: <div class="ui star rating" data-rating="<%= hotel.review.rating %>" data-max-rating="5"></div></div>
          <%= link_to semantic_icon('clipboard')+'Show more', hotel, class: 'ui right floated teal button' %>
        </div>
    </div>
  <% end %>
<% end %>

<div class="center aligned"><%= will_paginate @hotels, renderer: WillPaginateSemanticUi::ActionView::Renderer %></div>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $(".rating").rating('disable');
      $('.message .close').on('click', function() {
        $(this).closest('.message').transition('fade');
      });
  });
</script>

<div class="cover"></div>

<h1 id="top">Information</h1>

<br>

  <div class="ui fluid card">
    <div class="content">
      <div class="ui fluid teal ribbon label">
        <h1 class="center aligned header"><i class="hotel icon"></i> <%= @hotel.name %></h1>
        <div class="center aligned meta"><%= @hotel.address %></div>
        <div class="center aligned meta"><%= @hotel.city %></div>
      </div>
      <div id="map"></div>
      <script>
        function initMap() {
          var uluru = {lat: <%= @hotel.latitude %>, lng: <%= @hotel.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: uluru
          });
          var marker = new google.maps.Marker({
            position: uluru,
            map: map
          });
        }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFPP84MF3L9WqW4jcu5fAv709snqLSitg&callback=initMap">
      </script>
      <div class="ui divider"></div>
      <div class="description">
        <p><%= @hotel.review.title %></p>
        <p><%= @hotel.review.text %></p>
      </div>
    </div>
    <div class="extra content">
      <div class="ui large label">Rating: <div class="ui star rating" data-rating="<%= @hotel.review.rating %>" data-max-rating="5"></div></div>
    </div>
    <div class="content">
    <h3 class="ui header"><i class="comment icon"></i> Comments:</h3>
    <% if @hotel_comments.count == 0 %>
      <div class="ui fluid teal label">
        <div class="description">
          <p class="center aligned">No comments found.</p>
        </div>
      </div>
    <% else %>
      <%= render 'comments/comment', obj: @hotel_comments %>
    <% end %>
    <div class="center aligned"><%= will_paginate @hotel_comments, renderer: WillPaginateSemanticUi::ActionView::Renderer %></div>
    <div class="ui divider"></div>
    <%= render 'form' %>
    <div class="ui divider"></div>
    <%= link_to semantic_icon('left chevron')+'Back', hotels_path, class: 'fluid ui teal button' %>
    </div>
  </div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="ui borderless labeled icon menu">
        <div class="item center">
            <p>Made by Ivan Landeka &amp; Kristijan Prevolsek.</p>
            <p>RIT &copy; 2018</p>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>  
    <div class="ui grid center aligned">
        <div class="ui container">
            <div class='ui large <%="#{name}"%> message'>
                <i class="close icon"></i>
                <div class="header">
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui borderless top fixed menu navbar">
    <div class="item">
        <i class="large h square icon"></i>
        <%= link_to 'Hotel Reviews', hotels_path %>
    </div>
    <% if current_page?(hotels_path) || current_page?(root_path) %> 
        <div class="ui right category search item">
            <%= form_tag hotels_path, method: :get do %>
                <div class="ui action left icon input">
                    <i class="search link icon"></i>
                    <%= text_field_tag :search, params[:search], placeholder: 'Search for Hotel reviews...', class: 'nav-search' %>
                    <%= button_tag 'Search', name:nil, class: 'ui teal button', data: {disable_with: "<i class='
                    spinner loading icon'></i> Searching..."} %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel Reviews</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'hotel_icon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <%= render 'layouts/messages' %>

    <div class="ui container">
        <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>